export type ProjectCategory = "all" | "shop" | "food" | "service" | "custom";
export type ProjectStatus = "live" | "proprietary" | "concept";

export type ProjectItem = {
  id: string;
  title: string;
  titleEn: string;
  subtitle: string;
  subtitleEn: string;
  niche: string;
  nicheEn: string;
  desc: string;
  descEn: string;
  image: string;
  category: Exclude<ProjectCategory, "all">;
  status: ProjectStatus;
  url?: string;
  domain?: string;
  techStack: string[];
  features: string[];
  featuresEn: string[];
  featuredLanding: boolean;
};

export const ALL_PROJECTS: ProjectItem[] = [
  {
    id: "dehghani-gallery",
    title: "گالری فرش دهقانی",
    titleEn: "Dehghani Carpet Gallery",
    subtitle: "فروشگاه تخصصی فرش‌های دستباف و مدرن تبریز و کاشان",
    subtitleEn: "Luxury Persian Handmade & Modern Carpets E-Commerce",
    niche: "صنایع دستی و لوکس",
    nicheEn: "Luxury & Handmade Carpets",
    desc: "طراحی و توسعه فروشگاه آنلاین فرش‌های اصیل ایرانی با هویت بصری لوکس، کاتالوگ دقیق مشخصات رج، الیاف و بافت، ورود آسان با پیامک OTP، و بهینه‌سازی کامل موتورهای جستجو.",
    descEn: "Bespoke e-commerce experience for authentic Persian carpets, featuring intricate weave catalogs, SMS OTP authentication, and high-conversion UX.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-dehghani.webp`,
    category: "shop",
    status: "live",
    url: "https://dehghanigallery.com/",
    domain: "dehghanigallery.com",
    techStack: ["WordPress", "WooCommerce", "قالب اختصاصی Jiawaz", "لاگین پیامکی OTP", "RankMath SEO"],
    features: [
      "کاتالوگ جامع فرش‌های دستباف با فیلتر ابعاد و رج",
      "سیستم احراز هویت سریع پیامکی بدون رمز عبور",
      "تجربه کاربری لوکس و متناسب با خریداران کالای نفیس",
      "سئو ساختاریافته محصولات با رتبه‌گیری در کلمات کلیدی هدف",
    ],
    featuresEn: [
      "Comprehensive carpet catalog with knot & size filters",
      "Passwordless SMS OTP customer authentication",
      "Ultra-premium UI tuned for high-ticket luxury buyers",
      "Structured schema markup and top SEO rankings",
    ],
    featuredLanding: true,
  },
  {
    id: "ila-cafe",
    title: "کافه ایلا",
    titleEn: "ILA Café",
    subtitle: "وب‌سایت و منوی دیجیتال تعاملی کافه تخصصی و بیکری",
    subtitleEn: "Specialty Coffee House & Interactive Digital Menu",
    niche: "کافه و رستوران",
    nicheEn: "Specialty Coffee & Bakery",
    desc: "طراحی و پیاده‌سازی منوی دیجیتال تعاملی و وب‌سایت کافه ایلا؛ دسترسی آنی مشتریان سر میزها با اسکن QR، نمایش دسته‌بندی‌های قهوه تخصصی، بار سرد، ماچا و صبحانه با بارگذاری فوق‌سریع.",
    descEn: "Interactive digital menu and branding website for ILA Café, enabling instant QR table access, specialty brew showcase, and touch-optimized navigation.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-ilacafe.webp`,
    category: "food",
    status: "live",
    url: "http://ilacafe.ir/",
    domain: "ilacafe.ir",
    techStack: ["WordPress", "قالب اختصاصی Ila Cafe", "منوی لمسی QR", "Mobile-First", "تایپوگرافی اختصاصی"],
    features: [
      "اسکن آنی کیوآرکد روی میزها بدون نیاز به نصب اپلیکیشن",
      "تفکیک شفاف لاین‌های قهوه دمی، نوشیدنی‌های سرد و ماچا",
      "طراحی گرم، مینیمال و متناسب با اتمسفر کافه",
      "سرعت بارگذاری فوق‌العاده روی اینترنت موبایل و شبکه‌های داخلی",
    ],
    featuresEn: [
      "Instant table QR scanning without app download",
      "Clear categorisation of specialty brews, cold bar & matcha",
      "Warm minimalist design mirroring the café's physical atmosphere",
      "Lightning-fast load speed over mobile cellular networks",
    ],
    featuredLanding: true,
  },
  {
    id: "game-land",
    title: "گیم لند",
    titleEn: "Game Land",
    subtitle: "پلتفرم تخصصی خرید سی‌پی کالاف دیوتی و ارز بازی‌های آنلاین",
    subtitleEn: "Gaming Currency & Mobile Game Recharge Platform",
    niche: "خدمات آنلاین و گیمینگ",
    nicheEn: "Gaming & Digital Products",
    desc: "طراحی و توسعه سامانه پربازدید خدمات گیمینگ و شارژ اکانت‌های بازی با تمرکز بر خرید امن سی‌پی (CP) کالاف دیوتی، تحویل فوری سفارشات، درگاه پرداخت شتاب و پنل پیگیری لحظه‌ای مشتری.",
    descEn: "High-volume gaming platform for in-game currencies and Call of Duty Mobile CP, engineered for lightning delivery, trusted payments, and live order tracking.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-gameland.webp`,
    category: "shop",
    status: "live",
    url: "https://game1and.com/",
    domain: "game1and.com",
    techStack: ["WordPress", "WooCommerce", "سامانه پردازش سفارشات", "درگاه پرداخت بانکی", "طراحی گیمینگ UI"],
    features: [
      "سیستم سفارش‌گیری سریع پکیج‌های سی‌پی فوری و زمان‌بر",
      "رابط کاربری جذاب و پویا با استایل ترند گیمینگ",
      "اتصال به درگاه‌های پرداخت امن و پیگیری خودکار وضعیت سفارش",
      "معماری بهینه‌سازی‌شده برای ترافیک بالای کمپین‌ها و جشنواره‌ها",
    ],
    featuresEn: [
      "Instant & discounted CP pack selection with live prices",
      "High-energy gaming UI/UX designed for player engagement",
      "Secure banking gateway integration with instant order status",
      "Optimized infrastructure handling massive campaign traffic spikes",
    ],
    featuredLanding: true,
  },
  {
    id: "fz-piercing",
    title: "اف‌زد پیرسینگ",
    titleEn: "FZ Piercing",
    subtitle: "فروشگاه تخصصی زیورآلات و پیرسینگ استیل ضدحساسیت",
    subtitleEn: "Hypoallergenic Stainless Steel Piercing & Jewelry",
    niche: "اکسسوری و مد",
    nicheEn: "Fashion & Body Jewelry",
    desc: "طراحی فروشگاه تخصصی پیرسینگ و زیورآلات با پالت ترند مدرن صورتی-مشکی، دسته‌بندی بر اساس نواحی بدن (گوش، بینی، لب و شکم)، ضمانت رنگ ثابت و ضدحساسیت و خرید آنلاین سریع.",
    descEn: "Modern e-commerce platform for hypoallergenic piercing jewelry, featuring chic aesthetics, anatomical placement filters, and seamless checkout.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-fzpiercing.webp`,
    category: "shop",
    status: "live",
    url: "http://fzpiercing.com/",
    domain: "fzpiercing.com",
    techStack: ["WordPress", "WooCommerce", "قالب اختصاصی aiweb", "درگاه شتاب", "Mobile-First"],
    features: [
      "دسته‌بندی ارگونومیک محصولات بر اساس نوع و موقعیت پیرسینگ",
      "هماهنگی کامل پالت بصری با سلیقه مخاطب اینستاگرامی نسل جدید",
      "فرآیند تسویه‌حساب آسان با حداقل فیلد در نسخه موبایل",
      "نمایش دقیق مشخصات متریال تیتانیوم و استیل ضدحساسیت",
    ],
    featuresEn: [
      "Ergonomic product categories filtered by piercing placement",
      "Trendy visual branding aligned with modern social commerce",
      "Frictionless mobile checkout flow with minimal form fields",
      "Detailed titanium & surgical steel material certifications",
    ],
    featuredLanding: true,
  },
  {
    id: "teb-irani",
    title: "نداهیر | طب ایرانی",
    titleEn: "NedaHair | Traditional Medicine",
    subtitle: "مرکز تخصصی مراقبت علمی و ارگانیک مو با هدایت ندا کفایتی",
    subtitleEn: "Organic Hair Wellness & Scalp Therapy Center",
    niche: "سلامت و زیبایی طبیعی",
    nicheEn: "Herbal Wellness & Scalp Care",
    desc: "طراحی و راه‌اندازی وبسایت و فروشگاه تخصصی درمان‌های گیاهی و ارگانیک مو با مدیریت ندا کفایتی؛ متمرکز بر اصلاح طبع، رویش مجدد مو، سیستم مشاوره اختصاصی و رضایت مراجعین.",
    descEn: "Holistic hair therapy and herbal products platform led by Neda Kefaayati, focusing on root-cause wellness, personalized consultation, and client testimonials.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-tebirani.webp`,
    category: "shop",
    status: "live",
    url: "https://tebirani1.ir/",
    domain: "tebirani1.ir",
    techStack: ["WordPress", "WooCommerce", "قالب اختصاصی گیاه‌بان", "فرم مشاوره آنلاین", "طراحی ارگانیک"],
    features: [
      "معماری محتوایی سلامت‌محور با پالت ارگانیک طبیعی و آرامش‌بخش",
      "فرم آنلاین ارزیابی وضعیت مو و درخواست مشاوره تخصصی",
      "نمایش مستند تجربیات مراجعین و نتایج درمان‌های ریشه‌ای",
      "سئوی محلی و آموزشی مقالات سلامت و مراقبت مو",
    ],
    featuresEn: [
      "Health-first layout with soothing organic aesthetics",
      "Interactive consultation assessment form for scalp analysis",
      "Documented client case studies and transformation results",
      "Local SEO and knowledge base covering herbal care practices",
    ],
    featuredLanding: true,
  },
  {
    id: "znz-perfume",
    title: "زد‌ان‌زد پرفیوم",
    titleEn: "ZNZ Perfume",
    subtitle: "فروشگاه تخصصی عطر، ادکلن‌های اورجینال و دکانت‌های نیش",
    subtitleEn: "Niche Fragrances, Decants & Luxury Perfumes",
    niche: "عطر و ادکلن لوکس",
    nicheEn: "Luxury Fragrances",
    desc: "طراحی فروشگاه آنلاین عطرهای نیش و لوکس با امکان تفکیک پیشرفته بر اساس نت‌های بویایی، طبع و فصل، تضمین ۱۰۰٪ اصالت کالا، بسته‌بندی نفیس و دسترسی سریع به دکانت‌های تست.",
    descEn: "Curated perfume destination for authentic niche fragrances and decants, with olfactive note filtering, seasonal recommendations, and secure packaging.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-znzperfume.webp`,
    category: "shop",
    status: "live",
    url: "http://znzperfiume.ir/",
    domain: "znzperfiume.ir",
    techStack: ["WordPress", "WooCommerce", "مگامنو روایح", "فیلتر پیشرفته نت‌ها", "طراحی دارک لوکس"],
    features: [
      "فیلترینگ تخصصی عطرها بر اساس طبع، فصل و ساختار رایحه",
      "معرفی دکانت‌های دست‌ساز برای تست اقتصادی قبل از خرید شیشه کامل",
      "طراحی دارک و جذاب متناسب با پرستیژ برندهای لوکس جهانی",
      "سیستم پیشنهاد هوشمند روایح مکمل و هم‌سلیقه",
    ],
    featuresEn: [
      "Advanced olfactive filtering by season, scent family and sillage",
      "Decant sample options for accessible testing before full bottle",
      "Sleek dark-mode aesthetic matching world-class perfume houses",
      "Intelligent scent recommender based on taste preferences",
    ],
    featuredLanding: true,
  },
  {
    id: "rubifo",
    title: "Rubifo (روبیفو)",
    titleEn: "Rubifo Automation",
    subtitle: "ربات هوشمند و وب‌اپلیکیشن اتوماسیون بارگذاری محتوا در روبیکا",
    subtitleEn: "Smart Content Automation & Publishing Bot for Rubika",
    niche: "نرم‌افزار و ابزار بازاریابی",
    nicheEn: "Marketing Automation",
    desc: "سامانه اتوماسیون هوشمند برای ادمین‌های کانال‌ها و کسب‌وکارهای فعال در روبیکا؛ بارگذاری خودکار محتوا، زمان‌بندی دقیق، درگاه پرداخت اختصاصی و پنل مدیریت متمرکز.",
    descEn: "Automated content scheduler and monetization bot tailored for Rubika channel managers, featuring web dashboard and automated payment verification.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-rubifo.webp`,
    category: "custom",
    status: "proprietary",
    techStack: ["Node.js", "Python Automation", "وب‌اپلیکیشن اختصاصی", "درگاه پرداخت بانکی", "سامانه وب‌هوک"],
    features: [
      "انتشار زمان‌بندی‌شده و خودکار پست‌ها در چندین کانال به صورت همزمان",
      "درگاه پرداخت یکپارچه برای خرید اشتراک و شارژ اعتبار ادمین",
      "داشبورد آنالیز تعاملات و بازخورد پست‌ها بدون نیاز به مداخله انسانی",
    ],
    featuresEn: [
      "Scheduled cross-channel posting with zero manual intervention",
      "Integrated banking gateway for subscription licensing",
      "Analytics dashboard monitoring audience reach and delivery rates",
    ],
    featuredLanding: false,
  },
  {
    id: "automarketing",
    title: "AutoMarketing",
    titleEn: "AutoMarketing AI",
    subtitle: "سیستم جامع دیجیتال مارکتینگ و تحلیل بازار مبتنی بر هوش مصنوعی",
    subtitleEn: "AI-Powered End-to-End Digital Marketing Intelligence",
    niche: "هوش مصنوعی و مارکتینگ",
    nicheEn: "AI & Marketing Tech",
    desc: "پلتفرم یکپارچه تحقیقات بازار، ایده‌پردازی و تولید سناریوهای تبلیغاتی با بهره‌گیری از مدل‌های زبانی پیشرفته هوش مصنوعی برای تسریع رشد کسب‌وکارهای آنلاین.",
    descEn: "Comprehensive marketing platform leveraging LLM pipelines to automate competitor research, content scripting, and marketing campaign optimization.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-automarketing.webp`,
    category: "custom",
    status: "concept",
    techStack: ["Next.js", "AI Agent Pipelines", "LLM Integration", "Tailwind CSS", "توسعه کانسپت"],
    features: [
      "اسکن رقبا و تولید ساختار یافته استراتژی محتوایی بر اساس داده‌های زنده",
      "تولید سناریوهای خلاقانه تبلیغاتی متناسب با پرسونای مخاطب ایرانی",
      "تحلیل احساسات و نرخ تبدیل کمپین‌های بازاریابی دیجیتال",
    ],
    featuresEn: [
      "Competitor scan and structured content blueprint generator",
      "Creative ad script engine fine-tuned for Iranian buyer psychology",
      "Sentiment and conversion analytics across digital funnels",
    ],
    featuredLanding: false,
  },
  {
    id: "loosipet",
    title: "LoosiPet (لوسی‌پت)",
    titleEn: "LoosiPet Digital ID",
    subtitle: "پلتفرم پلاک هوشمند و شناسنامه دیجیتال ابری حیوانات خانگی",
    subtitleEn: "Smart Pet Identification & AI Care Platform",
    niche: "استارتاپ و اینترنت اشیاء",
    nicheEn: "PetTech & Smart ID",
    desc: "پلتفرم پلاک هوشمند با کیوآرکد پویا و پروفایل ابری برای حفظ امنیت پت‌ها، اعلان لحظه‌ای به صاحب حیوان هنگام اسکن پلاک و دستیار هوشمند پرونده پزشکی.",
    descEn: "Smart dynamic QR pet tag connected to a cloud emergency profile, featuring location alerts upon scan and medical records management.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-loosipet.webp`,
    category: "custom",
    status: "concept",
    techStack: ["Next.js", "QR پویای ابری", "Geofencing", "پروفایل هوشمند", "Framer Motion"],
    features: [
      "پروفایل دیجیتال اضطراری با اسکن سریع کیوآرکد پلاک فیزیکی",
      "ارسال لوکیشن تقریبی یابنده به صاحب پت به صورت آنی",
      "ثبت واکسیناسیون، سوابق درمان و یادآورهای پزشکی",
    ],
    featuresEn: [
      "Instant emergency pet profile loaded via physical QR collar tag",
      "Real-time location notification dispatched to pet guardian",
      "Medical vaccination history and care calendar reminders",
    ],
    featuredLanding: false,
  },
  {
    id: "lux-counter",
    title: "Lux Counter (لوکس کانتر)",
    titleEn: "Lux Counter",
    subtitle: "وب‌سایت شرکتی و کاتالوگ ۲۰۰+ محصول صفحات سنگ کابینت و کانترتاپ",
    subtitleEn: "B2B Engineered Stone & Solid Surface Countertops",
    niche: "صنعت و دکوراسیون",
    nicheEn: "Industrial Interior & Stone",
    desc: "سایت شرکتی تخصصی برای معرفی سنگ‌های مهندسی‌شده، کورین و کوارتز با دسته‌بندی بیش از ۲۰۰ متریال، طراحی دوتمه مدرن و سیستم استعلام پروژه معماری.",
    descEn: "Industrial portfolio catalog showcasing 200+ solid surface slabs, featuring a dual-theme aesthetic and B2B project inquiry workflow.",
    image: `${process.env.NEXT_PUBLIC_BASE_PATH}/images/portfolio/portfolio-luxcounter.webp`,
    category: "service",
    status: "proprietary",
    techStack: ["WordPress", "کاتالوگ تخصصی سنگ", "طراحی دوتمه", "سئو صنعتی B2B"],
    features: [
      "کاتالوگ بیش از ۲۰۰ کد رنگی و بافت سنگ ساختمانی و کورین",
      "سیستم استعلام سریع قیمت برای معماران و مجریان دکوراسیون",
      "پشتیبانی از تم روشن و تاریک متناسب با سلیقه طراحان",
    ],
    featuresEn: [
      "Comprehensive catalog of 200+ engineered stone surface textures",
      "Rapid inquiry pipeline tailored for interior designers and architects",
      "Dual-theme day/night visual presentation for materials",
    ],
    featuredLanding: false,
  },
];

export const PORTFOLIO_FILTER_TABS: { key: ProjectCategory; labelFa: string; labelEn: string; labelAr: string }[] = [
  { key: "all", labelFa: "همه پروژه‌ها", labelEn: "All Projects", labelAr: "كل المشاريع" },
  { key: "shop", labelFa: "فروشگاهی و تجارت الکترونیک", labelEn: "E-Commerce", labelAr: "متاجر إلكترونية" },
  { key: "food", labelFa: "کافه، رستوران و منو دیجیتال", labelEn: "Café & Digital Menu", labelAr: "مقاهي وقوائم رقمية" },
  { key: "service", labelFa: "شرکتی و خدماتی", labelEn: "Corporate & Services", labelAr: "شركات وخدمات" },
  { key: "custom", labelFa: "سیستم‌های اختصاصی و استارتاپ", labelEn: "Custom Tech & Startups", labelAr: "أنظمة مخصصة وشركات ناشئة" },
];
